import recipe01Img from "../assets/image01.png";
import recipe02Img from "../assets/image02.jpeg";
import recipe03Img from "../assets/image03.png";
import recipe04Img from "../assets/image04.png";
import recipe05Img from "../assets/image05.jpeg";
import recipe06Img from "../assets/image06.jpeg";
import recipe07Img from "../assets/image07.jpeg";
import recipe08Img from "../assets/image08.jpeg";

export const getTopMatch = () => {
  return getAllRecipes();
};

export const getPersonalSuggestion = () => {
  return getAllRecipes();
};

export const getAllRecipes = () => {
  return [
    {
      id: 1,
      name: "Raspberry & coconut steamed sponge",
      link: "https://www.bbcgoodfood.com/recipes/raspberry-coconut-steamed-sponge",
      image: recipe01Img,
      shortDescription: "comforting and great for serving after Sunday lunch",
      description:
        "Need a no-fuss, make-ahead dessert that’s comforting and great for serving after Sunday lunch? Look no further than our raspberry and coconut steamed sponge",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "kcal", value: "665g" },
        { key: "fat", value: "37g" },
        { key: "saturates", value: "24g" },
        { key: "carbs", value: "72g" },
        { key: "sugars", value: "51g" },
        { key: "fiber", value: "2g" },
        { key: "protein", value: "10g" },
        { key: "salt", value: "0.5g" },
      ],
      ingredients: [
        "175g unsalted butter , softened, plus extra for the basins",
        "6 tbsp raspberry jam",
        "175g caster sugar",
        "3 large eggs",
        "150g self-raising flour",
        "25g desiccated coconut , blitzed in a small food processor until fine",
        "1 tsp vanilla extract",
        "2 tbsp coconut cream , plus 2 tbsp to serve (optional)",
        "500g thick custard , to serve",
      ],
      instructions: [
        "butter six small pudding basins and spoon 1 tbsp jam into the bottom of each one. ",
        "put the butter and sugar in a medium bowl and beat with an electric whisk until pale and fluffy. beat in one of the eggs followed by a spoonful of the flour, then continue until all the eggs have been incorporated. fold in the remaining flour, the coconut and a pinch of salt, then the vanilla and coconut cream. spoon the mix into the prepared basins, leaving a 1cm gap at the top. ",
        "put the basins on a baking tray, transfer to the freezer and freeze until solid. will keep in an airtight container, or tightly wrapped in the freezer for up to three months. ",
        "heat the oven to 180c/160c fan/ gas 4. put the basins in a deep baking dish and half-fill with boiled water from the kettle. tightly cover the dish with foil and bake for 1 hr, or until a skewer inserted into the middle of a sponge comes out clean.",
        "warm the custard with the remaining 2 tbsp coconut cream, if using, and pour into shallow bowls. run a knife around the sides of the basins and carefully turn out the sponges onto the custard.",
      ],
    },
    {
      id: 2,
      name: "Condensed milk custard filo pie",
      link: "https://www.taste.com.au/recipes/condensed-milk-custard-filo-pie-recipe/t3oy6685?r=recipes/9w1up3vs",
      image: recipe02Img,
      shortDescription: "Prep this pie in 10 minutes",
      description:
        "Prep this pie in 10 minutes, then watch jaws drop as you serve up those sweet, sticky, crunchy slices!",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "100g butter, melted",
        "10 sheets filo pastry",
        "395g can sweetened condensed milk",
        "250ml (1 cup) milk",
        "2 eggs",
        "1 tsp vanilla extract",
        "icing sugar, to dust",
      ],
      instructions: [
        "preheat the oven to 180c/160c fan. brush a 4.5cm-deep, 1.5l (6 cup) baking dish with a little melted butter.",
        "place 1 pastry sheet on a clean work surface. cover the remaining sheets with a clean, dry tea towel and then a damp tea towel. brush the pastry with a little melted butter. from 1 short end, drag the pastry until it forms an accordion-like strip about 2cm wide. place around the edge of the prepared dish. repeat with the remaining pastry sheets, working towards the center and scrunching slightly to fit as necessary, until the base of the dish is covered. place the dish on a baking tray. bake for 20 minutes or until golden and crisp. remove from the oven.",
        "whisk the sweetened condensed milk, milk eggs and vanilla in a jug until combined. carefully pour mixture all over the pastry. bake for 20 minutes or until set. set aside for 10 minutes to cool slightly. serve warm dusted with icing sugar.",
      ],
    },
    {
      id: 3,
      name: "STICKY TOFFEE PUDDING",
      link: "https://lovefoodies.com/sticky-toffee-pudding/",
      image: recipe03Img,
      shortDescription: "popular dessert in England",
      description:
        "This is a very popular dessert in Britain, often served warm with a delicious hot toffee sauce. Recipe here for Slow cooker, oven or steamer. You choose!",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "8 oz or 225 g cooking dates, stoned and chopped small",
        "¾ cup or 175 ml boiling water",
        "1 tsp vanilla extract",
        "1 ½ cups or 175 g self-raising flour",
        "1 tsp bicarbonate of soda",
        "2 large, fresh eggs, lightly beaten",
        "⅓ cup or 85 g butter , softened",
        "⅔ cup or 140 g demerara (brown) sugar",
        "2 tbsp black treacle / molasses",
        "½ cup or 100 ml milk sauce ",
        "¾ cup or 175 g light muscovado sugar",
        "¼ cup or 55 g butter , cubed",
        "1 cup or 225 ml heavy / double cream",
        "1 tbsp black treacle / molasses",
      ],
      instructions: [
        "grease your pudding basin, mini pots or ramekins or baking pan.",
        "cut a piece of parchment paper and place it in the base of your container . this will stop the pudding sticking later.",
        "put the chopped dates into a large bowl, add the boiling water, leave for 20 minutes. once soft, add the vanilla extract.",
        "sieve the flour and bicarbonate of soda into a separate bowl.",
        "in another bowl, cream the butter and sugar together until light and creamy, the sugar may not dissolve, but don't worry.",
        "slowly add the beaten eggs, mixing really well in between, then add the treacle and beat well.",
        "using a metal spoon fold in one half of the flour, then stir in one half of the milk. repeat until all the flour and milk is used up.",
        "add the chopped dates (including any liquid in the bowl) and stir gently. the pudding mixture will be a thick batter.",
        "divide the mixture between the pudding ramekins, or place in the large basin or baking pan.",
      ],
    },
    {
      id: 4,
      name: "Cookies & Cream Puffs",
      link: "https://tasty.co/recipe/cookies-cream-puffs?epik=dj0yJnU9cTVNbjJrWWp3NjYxZy1lWHQyajJka0hpUEpCb1FXekgmcD0wJm49WEwxcVlyb1pqUWhfN2h3ZU55VUxkZyZ0PUFBQUFBR0p1SVJz",
      image: recipe04Img,
      shortDescription: "Ice Cream Sandwiches",
      description:
        "Pastry meets ice cream in these delightfully crunchy, craquelin-topped cream puffs stuffed with cookies and cream ice cream.",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "25 chocolate sandwich cookies",
        "2 egg yolks",
        "2 cups half & half(480 ml)",
        "¼ cup granulated sugar(50 g)",
        "¼ cup cornstarch(30 g)",
        "1 cup water(240 ml)",
        "8 tablespoons butter",
        "½ cup flour(60 g)",
        "4 eggs",
      ],
      instructions: [
        "preheat oven to 425°f (220°c).",
        "using a knife, separate the cream from the cookies, and place them in two separate bowls.",
        "crush cookies in a blender or a food processor until fine. set aside.",
        "in a pot over low heat, combine egg yolks, half & half, sugar, and cornstarch. turn the heat up to medium-high, whisking constantly to prevent any lumps. once the mixture starts to thicken, add in half of the cookie cream, stirring until smooth.",
        "transfer the cream mixture into a bowl, covering the top with plastic wrap and pressing the wrap down onto the surface of the cream to prevent a skin from forming. chill.",
        "in a pot, combine the water and butter, bringing it to a boil. add the flour and ½ cup (40 grams) of the crushed cookie mixture, stirring until the dough comes together in a ball. remove from heat.",
        "add in the eggs one at a time, stirring until the dough becomes a paste. transfer the dough into a piping bag with a large round tip.",
        "on a baking sheet lined with parchment paper, pipe 1-inch mounds.",
        "bake for 20-25 minutes until the pastry has risen considerably and the insides are dry.",
        "transfer the chilled pastry cream into a piping bag with a small tip.",
        "poke a hole in the centre of the bottom of each cream puff and fill each puff with the pastry cream.",
        "microwave the remaining cookie cream for 30 seconds, stirring until smooth.",
        "dip the top of each filled cream puff into the cookie cream, dripping off any excess.",
        "sprinkle any remaining cookie crumbs on top of each cream puff.",
      ],
    },
    {
      id: 5,
      name: "Janet's Rich Banana Bread",
      link: "https://www.allrecipes.com/recipe/17066/janets-rich-banana-bread/",
      image: recipe05Img,
      shortDescription: "moistest banana bread",
      description:
        "This is the moistest banana bread that I have ever tasted. It's also very easy to make!",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "½ cup butter, melted",
        "1 cup white sugar",
        "2 eggs",
        "1 teaspoon vanilla extract",
        "1½ cups all-purpose flour",
        "1 teaspoon baking soda",
        "½ teaspoon salt",
        "½ cup sour cream",
        "½ cup chopped walnuts",
        "2 medium bananas, sliced",
      ],
      instructions: [
        "preheat oven to 350 degrees f (175 degrees c). grease a 9x5 inch loaf pan.",
        "in a large bowl, stir together the melted butter and sugar. add the eggs and vanilla, mix well. combine the flour, baking soda and salt, stir into the butter mixture until smooth. finally, fold in the sour cream, walnuts and bananas. spread evenly into the prepared pan",
        "bake at 350 degrees f (175 degrees c) for 60 minutes, or until a toothpick inserted into the center of the loaf comes out clean. cool loaf in the pan for 10 minutes before removing to a wire rack to cool completely",
      ],
    },
    {
      id: 6,
      name: "Pineapple Upside-Down Cupcakes",
      link: "https://www.google.com/url?q=https://www.bettycrocker.com/how-to/tipslibrary/baking-tips/pineapple-upside-down-cupcakes?epik%3Ddj0yjnu9yty1tzblu3buczhqu3diy3uyefnwywdodnk3rhcwzlkmcd0wjm49n0fhnlhhzgviqmhnrxvvqzyzazg0zyz0pufbqufbr0p1sw44&sa=D&source=docs&ust=1652872002588547&usg=AOvVaw31Hek05i0nx7-8dyOP1Pxv",
      image: recipe06Img,
      shortDescription: "crowd-pleasing classic dessert",
      description:
        "Pineapple, warm butter, gooey brown sugar and cherries are the delicious flavors that make up a pineapple-upside down cake. Now you can have all those amazing tastes in a cupcake.",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "pineapple",
        "warm butter",
        "gooey brown sugar",
        "cherries",
      ],
      instructions: [
        "cut each pineapple slice into four pieces; set aside.",
        "in a large bowl, beat the cake mix, oil, eggs and reserved pineapple juice with an electric mixer on low speed for 30 seconds. beat on medium speed for 2 minutes, scraping the bowl occasionally",
        "in a small bowl, stir together melted butter and brown sugar. spoon 1-½ teaspoons into each muffin cup",
        "top each with two pineapple pieces. place a cherry half, cut side up, in the centre of the pineapple pieces",
        "spoon ¼ cup batter into each cup",
        "bake 20 to 25 minutes or until a toothpick inserted into the centre comes out clean. cool 5 minutes",
        "run a knife around the edge of the cupcakes to loosen. invert the pan onto a cookie sheet and lift up",
      ],
    },
    {
      id: 7,
      name: "Sticky-Toffee Dessert",
      link: "https://www.foodnetwork.com/recipes/nigella-lawson/easy-sticky-toffee-dessert-recipe-2203727",
      image: recipe07Img,
      shortDescription: "sticky toffee pudding",
      description:
        "An easy sticky toffee pudding – no steaming, no caramel to make, just tasty springy sponge and a treacle toffee sauce.",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "butter, for baking dish plus ¼ cup, melted",
        "scant ⅓ cup dark brown sugar, packed",
        "1 cup plus 2 tablespoons self-rising flour",
        "½ cup whole milk",
        "1 egg",
        "1 teaspoon vanilla extract",
        "¾ cup plus 2 tablespoons chopped, rolled dates sauce",
        "¾ cup dark brown sugar, packed",
        "approximately 2 tablespoons unsalted butter in little blobs",
        "2 ¼ cups boiling water",
      ],
      instructions: [
        "for the cake: preheat the oven to 375 degrees f and butter a 1 ½-quart capacity baking dish.",
        "combine the sugar with the flour in a large bowl. pour the milk into a measuring cup, beat in the egg, vanilla and melted butter and then pour this mixture over the sugar and flour, stirring with a wooden spoon to combine. fold in the dates then scrape into the prepared baking dish. don't worry if it doesn't look very full; it will by the time it cooks.",
        "for the sauce: sprinkle the sugar over the cake mixture and dot with butter. pour over the boiling water (yes really!) and transfer to the oven. set the time for 45 minutes, though you might find the dessert needs 5 or 10 minutes more. the top of the dessert should be springy and spongy when it's cooked; underneath, the butter, dark brown sugar and boiling water will have turned into a rich, sticky sauce. serve with vanilla ice cream, creme fraiche or heavy or light cream, as you wish.",
      ],
    },
    {
      id: 8,
      name: "Cheddars Texas Cheese Fries",
      link: "https://copykat.com/cheddars-texas-cheese-fries/",
      image: recipe08Img,
      shortDescription: "delicious French fries covered in cheese and bacon",
      description:
        "Cheddars Scratch Kitchen makes some of the best appetizers around. One of my favorite menu items is the Texas Cheese Fries. It is hard to beat these delicious French fries covered in cheese and bacon.",
      mood: "good",
      updatedOn: new Date(2022, 5, 1),
      cuisine: "Cake",
      culture: "Western",
      nutrient: [
        { key: "protein", value: "6.6g" },
        { key: "fat", value: "14.4g" },
        { key: "cholesterol", value: "0.1g" },
        { key: "carbohydrate", value: "34.8g" },
        { key: "sugars", value: "24.3g" },
        { key: "dietary-fiber", value: "0.4g" },
        { key: "sodium", value: "170.1mg" },
        { key: "calcium", value: "153.1mg" },
      ],
      ingredients: [
        "Frozen regular-cut French fries",
        "Bacon",
        "Shredded Cheddar-Jack cheese blend",
        "Ranch Salad Dressing",
        "Vegetable oil for frying",
      ],
      instructions: [
        "Deep fry the French fries in vegetable oil until they are golden and crisp. Drain fries on a wire cooling rack.",
        "Cook the bacon in a skillet over medium heat until brown and crispy. Drain on paper towels. Cut the bacon into pieces.",
        "Spread out the cooked French fries on an ovenproof platter, leaving a hole in the middle.",
        "Sprinkle shredded cheese and bacon pieces over the fries.",
        "Bake at 425 degrees for 7 to 8 minutes or until the cheese melts and begins to brown.",
        "Place a bowl of ranch dressing in the middle of the fries. Serve immediately.",
      ],
    },
  ];
};
